// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web1001_BookTracking;

#nullable disable

namespace Web1001_BookTracking.Migrations
{
    [DbContext(typeof(BookTrackingDbContext))]
    [Migration("20230816042306_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.19");

            modelBuilder.Entity("Web1001_BookTracking.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category_NameToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.HasIndex("Category_NameToken");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Web1001_BookTracking.Models.Category", b =>
                {
                    b.Property<string>("NameToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NameToken");

                    b.HasIndex("CategoryType");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Web1001_BookTracking.Models.CategoryType", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type");

                    b.ToTable("CategoryTypes");
                });

            modelBuilder.Entity("Web1001_BookTracking.Models.Book", b =>
                {
                    b.HasOne("Web1001_BookTracking.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_NameToken")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Web1001_BookTracking.Models.Category", b =>
                {
                    b.HasOne("Web1001_BookTracking.Models.CategoryType", "CategoryTypeEntity")
                        .WithMany()
                        .HasForeignKey("CategoryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryTypeEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
